print ("How to date the coolest girl/guy in school!")
print ("    ")


plural_noun = input('Enter a plural noun: ')
adverb = input('Enter an adverb ending in "ly": ')
verb1 = input('Enter a verb not ending in "ing": ')
article_of_clothing = input('Enter an article of clothing: ')
body_part = input('Enter a body part: ')
adjective1 = input('Enter an adjective: ')
noun = input('Enter a noun: ')
plural_noun2 = input('Enter another plural noun: ')
body_part2 = input('Enter another body part: ')
plural_noun3 = input('Enter another plural noun: ')
body_part3 = input('Enter another body part: ')
noun2 = input('Enter another noun: ')
noun3 = input('Again, enter another noun: ')
verb_ing = input("Enter a verb ending in 'ing': ")
adjective2 = input('Enter another adjective: ')
adjective3 = input('Again, enter another adjective: ')
verb2 = input('Enter another verb not ending in "ing": ')

print ("    ")
print ("It's simple. Touch their " + plural_noun + ". Make him/her want to ")
print (adverb + " date you. Make sure you're always dressed")
print ("to " + verb1 + ". Each and every day, wear a/an " + article_of_clothing)
print ("that you know shows off your " + body_part + " to your " + adjective1)
print ("advantage and make your " + noun + " look like a million")
print (plural_noun2+ ". Even if the two of you make meaningful")
print (body_part2 + " contact, don't admit it. No hugs or")
print (plural_noun3 + ". Just shake his/her " + body_part3)
print ("firmly. And remember, when she/he asks you out, even though a")
print ("chill may run down your " + noun2 + " and you can't stop your")
print (noun3 + " from " + verb_ing+ ", just play it " + adjective2 + ".")
print ("Take a long pause before answering in a very " + adjective3 + " voice.")
print (" 'I'll have to " + verb2 + " it over.' ") 
